[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/VÍDEOS FINAIS/*.webm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "video/webm"

[[headers]]
  for = "/IMAGES/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/ICONS/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
